### ISSUE TITLE
What is the output of the model?

### ISSUE THREAD

**Issue by williamwung** [Pramit726/MobileNetV2-FoodClassifier#1]
Hi

What is the output of the model? List of Labelmap or only a number work with other labmap file.

Thank you

**Comment by Pramit726** [comment]
The output of the MobileNetV2 model is a numerical class index corresponding to the predicted class. To map this index to a human-readable label, you need to use a separate label map file. The model itself does not output the list of labels directly but works with a label map file for interpretation.

**Comment by williamwung** [comment]
Thanks alot. Where can I find the lable map file?

**Comment by Pramit726** [comment]
The output of the MobileNetV2 model is a numerical class index corresponding to the predicted class. When using the image_dataset_from_directory function in TensorFlow, you can access the .class_names attribute of the dataset to retrieve the class labels. You can then export these labels to a file format of your choice if needed. However, I did not export them to a file as it wasn't required for my implementation.
